import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SideBarNavigation } from "./components/shared/SideBar/SidebarNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shows app",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#3f117c" }}>
        <Providers>
          <SideBarNavigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
