import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SideBarNavigation } from "./components/shared/SideBar/SidebarNavigation";
import { Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  showSidebar: boolean;
}

export const metadata: Metadata = {
  title: "Shows app",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
  showSidebar
}: Readonly<{
  children: React.ReactNode;
  showSidebar: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#3f117c" }}>
        <Providers>
          {showSidebar && <SideBarNavigation />}
          <Flex flex="1" justify="flex-end" margin="20px ">
            {children}
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
