import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Container, Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shows app",
  description: "Generated by create next app"
};

export default function AuthLayout({
  children,
  showSidebar
}: Readonly<{
  children: React.ReactNode;
  showSidebar: boolean;
}>) {
  return (
    <Flex
      flex="1"
      justifyContent="center"
      margin="40px "
      alignItems="center"
      overflow="hidden"
    >
      <Container
        backgroundColor="brand.300"
        justifyContent="center"
        maxWidth="450px"
      >
        {children}
      </Container>
    </Flex>
  );
}
