import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Flex } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shows app",
  description: "Generated by create next app"
};

export default function AuthLayout({
  children,
  showSidebar
}: Readonly<{
  children: React.ReactNode;
  showSidebar: boolean;
}>) {
  return (
    <Flex flex="1" justify="flex-end" margin="20px ">
      {children}
    </Flex>
  );
}
